/**
 * Audit headers + checksums para artefactos generados (S7-2 / R-3).
 *
 * Cada artefacto generado por el CLI puede llevar un header de auditoría:
 *
 *   # Generated by: dd-cli client publish
 *   # Generated at: 2026-06-26T08:55:00Z
 *   # CLI version: 0.6.0
 *   # Checksum: sha256:<hex>  (sobre el body sin el header)
 *
 * Esto permite que `context validate` o `client refresh` detecten si
 * un archivo fue editado a mano vs auto-generado, y reaccionen
 * inteligentemente:
 *   - Auto-generado intacto → safe re-generar
 *   - Modificado a mano → preservar al regenerar (o avisar)
 *   - Sin header → asumir manual (artefactos pre-S7-2)
 *
 * Bajo D-8: la skill `/devflow-ia:client-refresh` puede pedir al
 * usuario qué hacer cuando detecta divergencia.
 *
 * Forward-compat con A-3 del rediseño: futuros artefactos pueden
 * incluir `editable_sections` para granularidad.
 */
import { createHash } from 'node:crypto';

export interface AuditHeader {
  generated_by: string;        // ej: "dd-cli client publish"
  generated_at: string;        // ISO timestamp
  cli_version: string;
  checksum: string;            // sha256 del body sin header
}

export interface ParsedAuditedFile {
  header: AuditHeader | null;
  body: string;
  body_checksum: string;
  matches_checksum: boolean;   // true si checksum del header coincide con body actual
}

const HEADER_PREFIX = '# ── DevFlow IA audit header ──';
const HEADER_SUFFIX = '# ──────────────────────────────';

/**
 * Hash del body. Normalizado a UTF-8, sin trailing whitespace.
 */
export function sha256Body(body: string): string {
  return createHash('sha256').update(body.trimEnd() + '\n').digest('hex');
}

/**
 * Construye el header de auditoría como comentario YAML/markdown.
 * Compatible con .yml, .md, .toml, cualquier formato que use `#` para comentarios.
 */
export function buildAuditHeader(opts: {
  generated_by: string;
  cli_version: string;
  body: string;
  generated_at?: string;
}): string {
  const ts = opts.generated_at ?? new Date().toISOString();
  const checksum = sha256Body(opts.body);
  return [
    HEADER_PREFIX,
    `# Generated by: ${opts.generated_by}`,
    `# Generated at: ${ts}`,
    `# CLI version:  ${opts.cli_version}`,
    `# Checksum:     sha256:${checksum}`,
    HEADER_SUFFIX,
    '',
  ].join('\n');
}

/**
 * Parsea un archivo audit-eado. Si no tiene header, retorna body intacto +
 * header: null + matches_checksum: false (no audit info).
 */
export function parseAuditedFile(content: string): ParsedAuditedFile {
  // Detectar header
  const startIdx = content.indexOf(HEADER_PREFIX);
  if (startIdx === -1) {
    // Sin header — archivo no audit-eado
    const bodyChecksum = sha256Body(content);
    return {
      header: null,
      body: content,
      body_checksum: bodyChecksum,
      matches_checksum: false,
    };
  }

  const endIdx = content.indexOf(HEADER_SUFFIX, startIdx);
  if (endIdx === -1) {
    // Header parcial — tratamos como sin header
    return {
      header: null,
      body: content,
      body_checksum: sha256Body(content),
      matches_checksum: false,
    };
  }

  const headerBlock = content.slice(startIdx, endIdx + HEADER_SUFFIX.length);
  const afterHeader = content.slice(endIdx + HEADER_SUFFIX.length);
  // Eliminar el newline inicial post-header si lo hay
  const body = afterHeader.startsWith('\n') ? afterHeader.slice(1) : afterHeader;

  // Parsear campos del header
  const getField = (label: string): string | null => {
    const m = headerBlock.match(new RegExp(`^#\\s+${label}:\\s+(.+)$`, 'm'));
    return m?.[1]?.trim() ?? null;
  };

  const checksumRaw = getField('Checksum');
  const checksum = checksumRaw?.replace(/^sha256:/, '') ?? '';
  const header: AuditHeader = {
    generated_by: getField('Generated by') ?? 'unknown',
    generated_at: getField('Generated at') ?? '',
    cli_version: getField('CLI version') ?? '',
    checksum,
  };

  const bodyChecksum = sha256Body(body);

  return {
    header,
    body,
    body_checksum: bodyChecksum,
    matches_checksum: checksum === bodyChecksum && checksum.length > 0,
  };
}

/**
 * Wrappea un body con audit header y retorna el contenido listo para escribir.
 *
 * Importante: el header DEBE escribirse SOBRE el body final exacto que se
 * va a persistir. Para evitar circularidad (header depende de body, body
 * no depende del header), calculamos el checksum sobre el body limpio.
 */
export function writeWithAudit(opts: {
  generated_by: string;
  cli_version: string;
  body: string;
}): string {
  const header = buildAuditHeader(opts);
  return header + opts.body;
}

/**
 * Verdad útil para `context validate`: el artefacto tiene header válido,
 * y el contenido coincide con el checksum del header.
 */
export function isAuditedAndUnmodified(content: string): boolean {
  const parsed = parseAuditedFile(content);
  return parsed.header !== null && parsed.matches_checksum;
}

/**
 * Útil para `client refresh` y `context render`: ¿este archivo fue
 * editado a mano (auditado pero checksum no coincide)?
 */
export function wasManuallyEdited(content: string): boolean {
  const parsed = parseAuditedFile(content);
  return parsed.header !== null && !parsed.matches_checksum;
}
