/**
 * Tests del audit header (S7-2).
 */
import { describe, it, expect } from 'vitest';
import {
  buildAuditHeader,
  parseAuditedFile,
  writeWithAudit,
  sha256Body,
  isAuditedAndUnmodified,
  wasManuallyEdited,
} from './audit.js';

describe('sha256Body', () => {
  it('mismo input → mismo hash', () => {
    expect(sha256Body('foo')).toBe(sha256Body('foo'));
  });

  it('inputs distintos → hashes distintos', () => {
    expect(sha256Body('foo')).not.toBe(sha256Body('bar'));
  });

  it('trim trailing whitespace antes de hashear (estable)', () => {
    // 'foo' y 'foo  \n\n' deberían hashear igual
    expect(sha256Body('foo')).toBe(sha256Body('foo  \n\n'));
  });

  it('preserva whitespace interno', () => {
    expect(sha256Body('foo bar')).not.toBe(sha256Body('foobar'));
  });
});

describe('buildAuditHeader', () => {
  it('incluye campos requeridos', () => {
    const h = buildAuditHeader({
      generated_by: 'dd-cli client publish',
      cli_version: '0.6.0',
      body: 'key: value\n',
    });
    expect(h).toContain('Generated by: dd-cli client publish');
    expect(h).toContain('CLI version:  0.6.0');
    expect(h).toContain('Checksum:     sha256:');
  });

  it('respeta timestamp custom', () => {
    const ts = '2026-01-01T00:00:00Z';
    const h = buildAuditHeader({
      generated_by: 'x',
      cli_version: '0.0.0',
      body: 'x',
      generated_at: ts,
    });
    expect(h).toContain(`Generated at: ${ts}`);
  });
});

describe('writeWithAudit + parseAuditedFile round-trip', () => {
  it('parsea header + recupera body intacto', () => {
    const original = 'client:\n  slug: iprsa\n';
    const wrapped = writeWithAudit({
      generated_by: 'test',
      cli_version: '0.6.0',
      body: original,
    });
    const parsed = parseAuditedFile(wrapped);
    expect(parsed.header).not.toBeNull();
    expect(parsed.header?.generated_by).toBe('test');
    expect(parsed.header?.cli_version).toBe('0.6.0');
    expect(parsed.body).toBe(original);
    expect(parsed.matches_checksum).toBe(true);
  });

  it('detecta edición manual', () => {
    const wrapped = writeWithAudit({
      generated_by: 'test',
      cli_version: '0.6.0',
      body: 'client:\n  slug: iprsa\n',
    });
    // Reemplazar el body por algo distinto preservando el header
    const tampered = wrapped.replace('slug: iprsa', 'slug: pdr');
    const parsed = parseAuditedFile(tampered);
    expect(parsed.header).not.toBeNull();
    expect(parsed.matches_checksum).toBe(false);
  });
});

describe('parseAuditedFile sin header', () => {
  it('retorna header: null cuando no hay header', () => {
    const parsed = parseAuditedFile('algo: random\nfoo: bar\n');
    expect(parsed.header).toBeNull();
    expect(parsed.body).toBe('algo: random\nfoo: bar\n');
    expect(parsed.matches_checksum).toBe(false);
  });

  it('header parcial (sin suffix) tratado como sin header', () => {
    const broken = '# ── DevFlow IA audit header ──\n# Generated by: x\n# Sin cierre\nbody';
    const parsed = parseAuditedFile(broken);
    expect(parsed.header).toBeNull();
  });
});

describe('isAuditedAndUnmodified', () => {
  it('true cuando header y checksum coinciden', () => {
    const wrapped = writeWithAudit({
      generated_by: 'x', cli_version: '0.0.0', body: 'a: 1\n',
    });
    expect(isAuditedAndUnmodified(wrapped)).toBe(true);
  });

  it('false cuando el body fue editado', () => {
    const wrapped = writeWithAudit({
      generated_by: 'x', cli_version: '0.0.0', body: 'a: 1\n',
    });
    expect(isAuditedAndUnmodified(wrapped.replace('a: 1', 'a: 2'))).toBe(false);
  });

  it('false cuando no hay header', () => {
    expect(isAuditedAndUnmodified('a: 1\n')).toBe(false);
  });
});

describe('wasManuallyEdited', () => {
  it('true solo cuando header existe y checksum no coincide', () => {
    const wrapped = writeWithAudit({
      generated_by: 'x', cli_version: '0.0.0', body: 'a: 1\n',
    });
    expect(wasManuallyEdited(wrapped)).toBe(false);  // no editado
    expect(wasManuallyEdited(wrapped.replace('a: 1', 'a: 99'))).toBe(true);
    expect(wasManuallyEdited('a: 1\n')).toBe(false);  // sin header, no es "editado"
  });
});
